<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/Site.master" CodeFile="Disclaimer.aspx.cs" Inherits="Disclaimer" %>

<asp:Content ID="content_box" ContentPlaceHolderID="MainContent" runat="server">
    <h1 align="center"><font color="#af0083">Disclaimer for Reiki Distance Healing Website</font></h1>
            <p> <font size="4" color="#0b6d1a">
The healing services and information offered at this website are not intended as a substitute for professional medical and/or psychiatric treatment and advice. Betsy is not a medical doctor that diagnoses conditions and/or prescribes any medications. Betsy is not a licensed practitioner of medical care. Her energy healing work with people and animals should be understood as a positve and complementary therapy to professional medical care. 
She always recommends people continue to work with and/or consult with a local (physical) medical practitioner you are comfortable with.  She recommends that you continue to follow medical treatment as prescribed by your chosen healthcare professional. Ultimately you are responsible for your own medical treatment and care, you are the one that makes the decision.
Betsy can not guarantee a cure or prevention of disease and she makes no claims in this regard. The most that can be said is she is an instrument of divine healing energies which act as a catalyst for your own self-healing. She never knows what the final result will be of the healing work she does, but she has seen some miracluous things. Many benefits have been experienced by others who have recieved my energy healings, but understand that what will be the result, depends upon many variables, the most important aspect being your own inner healer.
The information as articles on this web site is presented for the purpose of educational and free exchange of ideas and speech in relation to health, spirituality and awareness only. It is not intended to diagnose any physical or mental condition or to give advise. It is not intended as a substitute for the advice and treatment of a licensed professional. In the event that you use the information here for your own health, or for that of your animals, you are prescribing for yourself or your animals, which is your constitutional right and for which the author of this site (Betsy) assumes no responsibility or liability of any kind. The author of this website (Betsy) is neither a legal counselor nor a health practitioner, nor a veterinarian, nor a licensed health professional and makes no claims in this regard.
 If you have any questions about this disclaimer, please feel free to contact me and ask about it.
 </font>
</p>
</asp:Content>